package pi

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/entireio/cli/cmd/entire/cli/agent"
	"github.com/entireio/cli/cmd/entire/cli/paths"
)

// Compile-time interface assertions.
var _ agent.HookSupport = (*PiAgent)(nil)
var _ agent.RestoredSessionPathResolver = (*PiAgent)(nil)

const (
	extensionFileName = "index.ts"
	extensionDirName  = "entire"
	extensionMarker   = "Auto-generated by `entire enable --agent pi`"
)

func extensionPath(ctx context.Context) (string, error) {
	repoRoot, err := paths.WorktreeRoot(ctx)
	if err != nil {
		repoRoot, err = os.Getwd() //nolint:forbidigo // Intentional fallback for tests outside git repositories.
		if err != nil {
			return "", fmt.Errorf("failed to get current directory: %w", err)
		}
	}
	return filepath.Join(repoRoot, ".pi", "extensions", extensionDirName, extensionFileName), nil
}

// InstallHooks writes the Entire Pi extension into the current repository.
func (a *PiAgent) InstallHooks(ctx context.Context, localDev bool, force bool) (int, error) {
	path, err := extensionPath(ctx)
	if err != nil {
		return 0, err
	}

	command := "entire"
	if localDev {
		command = `go run "$(git rev-parse --show-toplevel)"/cmd/entire/main.go`
	}
	content := strings.ReplaceAll(extensionTemplate, `"`+entireCmdPlaceholder+`"`, strconv.Quote(command))

	if !force {
		existing, readErr := os.ReadFile(path) //nolint:gosec // Path is under repository .pi extension directory.
		if readErr == nil && string(existing) == content {
			return 0, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return 0, fmt.Errorf("failed to create Pi extension directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //nolint:gosec // Extension file must be readable by Pi.
		return 0, fmt.Errorf("failed to write Pi extension file: %w", err)
	}
	return 1, nil
}

// UninstallHooks removes the Entire Pi extension from the current repository.
func (a *PiAgent) UninstallHooks(ctx context.Context) error {
	path, err := extensionPath(ctx)
	if err != nil {
		return err
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove Pi extension file: %w", err)
	}
	return nil
}

// AreHooksInstalled checks whether the Entire Pi extension is installed.
func (a *PiAgent) AreHooksInstalled(ctx context.Context) bool {
	path, err := extensionPath(ctx)
	if err != nil {
		return false
	}
	data, err := os.ReadFile(path) //nolint:gosec // Path is under repository .pi extension directory.
	if err != nil {
		return false
	}
	return strings.Contains(string(data), extensionMarker)
}
